/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a shop user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated user and JWT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecated customer registration endpoint */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                410: components["responses"]["Gone"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Password reset request accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password with a valid token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description Password reset completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user and shop */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current authenticated user and shop */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current token revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all tokens issued before now for the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All user sessions revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List repair orders for the current shop */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: string;
                    tech_id?: string;
                    assigned_to?: string;
                    type?: string;
                    job_type?: string;
                    date_from?: string;
                    date_to?: string;
                    payment_status?: string;
                    payment_type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repair orders for the current shop */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepairOrderListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ros/from-schedule/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a repair order from a schedule entry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scheduleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repair order created from the schedule entry */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepairOrder"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ros/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk update repair order status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkStatusRequest"];
                };
            };
            responses: {
                /** @description Repair orders updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkStatusResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ros/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a repair order by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enriched repair order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepairOrder"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ros/{id}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice preview data for a repair order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice preview data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invoice"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers for the current shop */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customers ordered by name */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomersListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /** Create a customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerCreateRequest"];
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Customer"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a customer with linked vehicles and repair orders */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Update a customer */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated customer, or null when the id is missing */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Customer"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        post?: never;
        /** Delete a customer */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List unread notifications for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest unread notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationsListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all current-user notifications as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notifications marked as read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification marked as read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/invoice/public/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a public invoice PDF by token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice PDF */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                410: components["responses"]["Gone"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoice/{roId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an invoice PDF for a repair order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice PDF */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimate-items/{roId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List estimate line items for a repair order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estimate line items and current summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateItemsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /** Create an estimate line item */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EstimateLineItemCreateRequest"];
                };
            };
            responses: {
                /** @description Estimate line item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateItemMutationResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimate-items/{roId}/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an estimate line item */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EstimateLineItemUpdateRequest"];
                };
            };
            responses: {
                /** @description Estimate line item updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateItemMutationResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        post?: never;
        /** Delete an estimate line item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estimate line item deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateItemDeleteResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimate-items/{roId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get estimate totals for a repair order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estimate summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateSummaryResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimate-items/{roId}/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analyze estimate profit opportunities */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profit opportunity analysis */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstimateOpportunitiesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeclock/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's clock-in status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current clock-in status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeclockStatusResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeclock/in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clock in the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TimeclockClockRequest"];
                };
            };
            responses: {
                /** @description User clocked in */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeclockClockInResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeclock/clock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clock in the current user using the alias route */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TimeclockClockRequest"];
                };
            };
            responses: {
                /** @description User clocked in */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeclockClockInResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeclock/out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clock out the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TimeclockClockRequest"];
                };
            };
            responses: {
                /** @description User clocked out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeclockClockOutResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeclock/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timeclock entries */
        get: {
            parameters: {
                query?: {
                    user_id?: string;
                    date_from?: string;
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Timeclock entries visible to the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeclockEntriesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shop notification settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current shop settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update shop notification settings */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated shop settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/settings/reset/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a shop data section */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    section: "ros" | "customers" | "vehicles" | "timeclock" | "all";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reset operation completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsResetResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message?: string | null;
            shiftStart?: string | null;
        } & {
            [key: string]: unknown;
        };
        OkResponse: {
            ok: boolean;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: string;
            /** Format: uuid */
            shop_id: string | null;
            /** Format: uuid */
            customer_id: string | null;
            onboarded: boolean;
        } & {
            [key: string]: unknown;
        };
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthLoginResponse: {
            token: string;
            user: components["schemas"]["AuthUser"];
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        Shop: {
            /** Format: uuid */
            id: string;
            name: string;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            onboarded?: boolean | null;
            sms_notifications_enabled?: boolean | null;
            email_notifications_enabled?: boolean | null;
            labor_rate?: number | null;
            parts_markup?: number | null;
            tax_rate?: number | null;
            logo_url?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        AuthMeResponse: {
            user: components["schemas"]["AuthUser"];
            shop: components["schemas"]["Shop"];
        };
        Customer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id: string;
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            address?: string | null;
            insurance_company?: string | null;
            policy_number?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        CustomerWithPortalAccess: components["schemas"]["Customer"] & {
            has_portal_access: boolean;
        };
        Vehicle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id?: string | null;
            /** Format: uuid */
            customer_id?: string | null;
            year?: number | null;
            make?: string | null;
            model?: string | null;
            vin?: string | null;
            color?: string | null;
            plate?: string | null;
            mileage?: number | null;
            /** Format: date-time */
            created_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        CustomerRepairOrderSummary: {
            /** Format: uuid */
            id?: string | null;
            ro_number: string | null;
            status: string | null;
            job_type: string | null;
            /** Format: date-time */
            created_at: string | null;
        } & {
            [key: string]: unknown;
        };
        CustomerDetail: components["schemas"]["Customer"] & {
            vehicles: components["schemas"]["Vehicle"][];
            ros: components["schemas"]["CustomerRepairOrderSummary"][];
        };
        CustomersListResponse: {
            customers: components["schemas"]["Customer"][];
        };
        CustomerCreateRequest: {
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            address?: string | null;
            insurance_company?: string | null;
            policy_number?: string | null;
        };
        CustomerUpdateRequest: {
            name?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            address?: string | null;
            insurance_company?: string | null;
            policy_number?: string | null;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            type: string;
            title: string;
            body?: string | null;
            /** Format: uuid */
            ro_id?: string | null;
            ro_number?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            read: boolean;
        } & {
            [key: string]: unknown;
        };
        NotificationsListResponse: {
            notifications: components["schemas"]["Notification"][];
            unread: number;
        };
        AssignedTech: {
            /** Format: uuid */
            id: string;
            name: string;
            role: string;
        } & {
            [key: string]: unknown;
        };
        ProfitSummary: {
            gross: number;
            cogs: number;
            naiveProfit: number;
            nyAdjustments: number;
            trueProfit: number;
            margin: number;
        };
        RepairOrderLogEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ro_id?: string;
            from_status?: string | null;
            to_status: string;
            changed_by?: string | null;
            note?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        PartOrder: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id?: string | null;
            /** Format: uuid */
            ro_id?: string | null;
            part_name: string;
            part_number?: string | null;
            vendor?: string | null;
            quantity?: number | null;
            unit_cost?: number | null;
            status?: string | null;
            /** Format: date-time */
            ordered_date?: string | null;
            /** Format: date-time */
            expected_date?: string | null;
            /** Format: date-time */
            received_date?: string | null;
            notes?: string | null;
            tracking_number?: string | null;
            carrier?: string | null;
            tracking_status?: string | null;
            tracking_detail?: string | null;
            /** Format: date-time */
            tracking_updated_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        RepairOrderBase: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id: string;
            ro_number?: string | null;
            /** Format: uuid */
            vehicle_id?: string | null;
            /** Format: uuid */
            customer_id?: string | null;
            /** Format: uuid */
            assigned_to?: string | null;
            job_type?: string | null;
            status?: string | null;
            payment_type?: string | null;
            payment_status?: string | null;
            /** Format: date-time */
            intake_date?: string | null;
            /** Format: date-time */
            estimated_delivery?: string | null;
            /** Format: date-time */
            actual_delivery?: string | null;
            parts_cost?: number | null;
            labor_cost?: number | null;
            sublet_cost?: number | null;
            tax?: number | null;
            total?: number | null;
            notes?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        RepairOrderListItem: components["schemas"]["RepairOrderBase"] & {
            year?: number | null;
            make?: string | null;
            model?: string | null;
            color?: string | null;
            customer_name?: string | null;
            customer_phone?: string | null;
        };
        RepairOrderListResponse: {
            ros: components["schemas"]["RepairOrderListItem"][];
        };
        RepairOrder: components["schemas"]["RepairOrderBase"] & {
            vehicle?: components["schemas"]["Vehicle"];
            customer?: components["schemas"]["CustomerWithPortalAccess"];
            log: components["schemas"]["RepairOrderLogEntry"][];
            parts: components["schemas"]["PartOrder"][];
            profit: components["schemas"]["ProfitSummary"];
            assigned_tech?: components["schemas"]["AssignedTech"];
        };
        BulkStatusRequest: {
            ids: string[];
            status?: string;
            new_status?: string;
        };
        BulkStatusResponse: {
            updated: number;
        };
        DeliveryFeeLeg: {
            enabled: boolean;
            miles: number;
            zone: string;
            method: string;
            rate?: number | null;
            applied_zone?: string | null;
            amount: number;
        } & {
            [key: string]: unknown;
        };
        DeliveryFeeBreakdown: {
            fee_type: string;
            flat_fee: number;
            per_mile_rate: number;
            default_zone_fee: number;
            zone_fees: {
                [key: string]: number;
            };
            delivery: components["schemas"]["DeliveryFeeLeg"];
            pickup: components["schemas"]["DeliveryFeeLeg"];
            total_fee: number;
        } & {
            [key: string]: unknown;
        };
        Invoice: components["schemas"]["RepairOrder"] & {
            shop: components["schemas"]["Shop"];
            delivery_fee_breakdown: components["schemas"]["DeliveryFeeBreakdown"];
            invoice_total_with_delivery: number;
        };
        EstimateLineItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ro_id: string;
            /** Format: uuid */
            shop_id: string;
            /** @enum {string} */
            type: "labor" | "parts" | "sublet" | "other";
            description: string;
            quantity: number;
            unit_price: number;
            total: number;
            taxable: boolean;
            sort_order: number;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        EstimateLineItemCreateRequest: {
            /** @enum {string} */
            type?: "labor" | "parts" | "sublet" | "other";
            description?: string;
            quantity?: number;
            unit_price?: number;
            taxable?: boolean;
            sort_order?: number;
        };
        EstimateLineItemUpdateRequest: {
            /** @enum {string} */
            type?: "labor" | "parts" | "sublet" | "other";
            description?: string;
            quantity?: number;
            unit_price?: number;
            taxable?: boolean;
            sort_order?: number;
        };
        EstimateSummary: {
            subtotal: number;
            labor_total: number;
            parts_total: number;
            sublet_total: number;
            other_total: number;
            taxable_subtotal: number;
            tax_rate: number;
            tax_amount: number;
            grand_total: number;
            line_count: number;
        };
        EstimateItemsResponse: {
            success: boolean;
            items: components["schemas"]["EstimateLineItem"][];
            summary: components["schemas"]["EstimateSummary"];
        };
        EstimateItemMutationResponse: {
            success: boolean;
            item: components["schemas"]["EstimateLineItem"];
            summary: components["schemas"]["EstimateSummary"];
        };
        EstimateItemDeleteResponse: {
            success: boolean;
            /** Format: uuid */
            deleted_id: string;
            summary: components["schemas"]["EstimateSummary"];
        };
        EstimateSummaryResponse: {
            success: boolean;
            summary: components["schemas"]["EstimateSummary"];
        };
        EstimateShopRates: {
            labor_rate: number;
            paint_rate: number;
            parts_markup: number;
        };
        EstimateOpportunitiesSummary: {
            line_count: number;
            labor_undercut_count: number;
            review_count: number;
            total_supplement_opportunity: number;
            current_grand_total: number;
            projected_grand_total: number;
            current_true_profit: number;
            projected_true_profit: number;
            profit_uplift: number;
        };
        EstimateOpportunityFlag: {
            /** Format: uuid */
            item_id?: string | null;
            type: string;
            description: string;
            quantity?: number | null;
            insurance_rate?: number | null;
            shop_rate?: number | null;
            gap_per_unit?: number | null;
            supplement_opportunity: number;
            message?: string | null;
        } & {
            [key: string]: unknown;
        };
        EstimateOpportunitiesResponse: {
            success: boolean;
            shop_rates: components["schemas"]["EstimateShopRates"];
            summary: components["schemas"]["EstimateOpportunitiesSummary"];
            flags: components["schemas"]["EstimateOpportunityFlag"][];
        };
        TimeclockUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: string;
        };
        TimeclockEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            shop_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            /** Format: date-time */
            clock_in?: string | null;
            /** Format: date-time */
            clock_out?: string | null;
            clock_in_lat?: number | null;
            clock_in_lng?: number | null;
            clock_out_lat?: number | null;
            clock_out_lng?: number | null;
            scheduled_start?: string | null;
            is_late?: number | null;
            late_minutes?: number | null;
            unscheduled_approved_by?: string | null;
            /** Format: date-time */
            unscheduled_approved_at?: string | null;
            total_hours?: number | null;
            adjusted_by?: string | null;
            admin_note?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            user?: components["schemas"]["TimeclockUser"];
        } & {
            [key: string]: unknown;
        };
        TimeclockClockRequest: {
            lat?: number | null;
            lng?: number | null;
        };
        TimeclockStatusResponse: {
            clocked_in: boolean;
            entry: components["schemas"]["TimeclockEntry"];
        };
        TimeclockClockInResponse: {
            entry: components["schemas"]["TimeclockEntry"];
            is_late: number;
            late_minutes: number;
            scheduled_start: string | null;
        };
        TimeclockClockOutResponse: {
            entry: components["schemas"]["TimeclockEntry"];
            total_hours: number;
        };
        TimeclockEntriesResponse: {
            entries: components["schemas"]["TimeclockEntry"][];
        };
        Settings: {
            sms_notifications_enabled: boolean;
            email_notifications_enabled: boolean;
        };
        SettingsUpdateRequest: {
            sms_notifications_enabled?: boolean;
            email_notifications_enabled?: boolean;
        };
        SettingsResetResponse: {
            ok: boolean;
            deleted: {
                [key: string]: number;
            };
        };
    };
    responses: {
        /** @description Validation failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid auth */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Permission denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict with current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource or flow is no longer available */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
